<?php
\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'codeNav'),
		array('name'=>'contentObj')
	)));

$request = Zend_Controller_Front::getInstance()->getRequest();
$this->headTitle($request->getActionName().'/')
     ->headTitle($request->getControllerName());

$contentArray=$this->contentObj->contentArray;


$outString=$contentArray['index.html'];
$elementList=$contentArray['elements'];

foreach ($elementList as $label=>$data){
	$outString=str_replace("elements/$label", $data, $outString);
}

?>
<?php  echo $outString;?>
