<?php

$headNavInfo = $this->contentArray['globalItems']['COMPONENTS']['headNav.ini'];

$menuBar = '';
foreach ($headNavInfo as $label => $data) {
	
	if ($label == 'title') {
		$titleNav = $this->assembleAnchor($headNavInfo['title']);
	} else {
		$this->dropDownParms = array("content" => $data, "specs" => array("navLocationClass" => $label));
		$menuBar.= $this->render('default/foundationComponents/dropdown-menu.phtml');
	}
}

echo "
  <nav class='top-bar' data-topbar role='navigation' style='z-index:100;position:fixed;top:0px;left:0px;width:100vw;'>
  <ul class='title-area'>
    <li class='name'>
      <h1>$titleNav</h1>
    </li>
     <!-- Remove the class 'menu-icon' to get rid of menu icon. Take out 'Menu' to just have icon alone -->
    <li class='toggle-topbar menu-icon'><a href='#'><span>Menu</span></a></li>
  </ul>

<section class='top-bar-section'>
$menuBar
  </section>

    <!-- Left Nav Section 
    <ul class='left'>
      <li><a href='#'>Left Nav Button</a></li>
    </ul>
    Left Nav Section -->
</nav>
";
