<?php
\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'codeNav'),
		array('name'=>'routes')
	)));

$outString='';
$outArray=array();

function makeArray($sub, $url, &$outArray){
	$element=array_shift($sub);

	while ($element=='' && count($sub)>0){$element=array_shift($sub);}

if (isset($outArray[$element])){
	if (count($sub)>0){
		$outArray[$element][]=makeArray($sub, $url, $outArray);
	}
	else{
			$outArray[$element]=$url;
	}

}

	if (count($sub)>0){
		if (isset($outArray[$element])){
	echo "elementa=$element<BR>";
			$outArray[$element][]=makeArray($sub, $url, $outArray);
		}
		else{
	echo "elementb=$element<BR>";
			$outArray[$element]=makeArray($sub, $url, $outArray);
		}
	}
	else{
	echo "elementc=$element<BR>";
		if ($element){
		$outArray[$element]=$url;
		}
	}
}

		foreach ($this->routes['routes'] as $label=>$data){

				if (isset($data['noList']) && $data['noList']==true){continue;}

				$url=$_SERVER['HTTP_HOST'].$data['route'];
				if (isset($data['title'])){
					$title=$data['title'];
				}
				else{
					$title=$url;
				}

				$pathComponents=explode('/', $data['route']?$data['route']:'/parent/');

\Q\Utils::dumpWeb($pathComponents, "pathComponents-$url");
				$outArray[]=makeArray($pathComponents, $url, $outArray);

\Q\Utils::dumpWeb($outArray, 'workingOUtArray');
echo "<div style='background:red;height:10px;width:100%;'></div>";
				$outString.="<li><a href='http://$url'>$title</a></li>";
				$items[$data['route']]="<a href='http://$url'>$title</a>";
		}
\Q\Utils::dumpWeb($outArray, 'outArray');
$outString="<ul>$outString</UL>";
$outString=$this->htmlList($items, false, array('id'=>'siteList'), false);
echo $outString;

?>

