<?php
\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'routes'),
		array('name'=>'section', 'importance'=>'optional')
	)));

$outString='';
$outArray=array();

function removeEmpty($inArray){
		$outArray=array();
			foreach ($inArray as $label=>$data){
				if ($data){$outArray[$label]=$data;}
		}
		return $outArray;
}

function makeArray($sub, $url, &$outArray){

	$element=array_shift($sub);


	if (!isset($outArray[$element])){
		$outArray[$element]=array();
	}

		$working=&$outArray[$element];

			if (!isset($working['links'])){ $working['links']=array();}
		if (count($sub)===0){
			$working['url']=$url;
		}
		else{
			makeArray($sub, $url, $working['links']);
		}

}

//=======================

		foreach ($this->routes['routes'] as $label=>$data){

				if (isset($data['noList']) && $data['noList']==true){continue;}
				if (isset($this->section) && !preg_match('/'.str_replace('/', '\\/', $this->section).'/', $data['route'])){continue;}


				if (isset($data['defaults']['title'])){
					$title=$data['defaults']['title'];
				}
				else{
					$title=$url;
				}

			if (preg_match('/http:/', $data['route'])){
				$outString.="<li class='sitemapItem'><a href='{$data['route']}'>$title</a></li>";
			}
			else{
				$url=$_SERVER['HTTP_HOST'].$data['route'];

				$pathComponents=explode('/', $data['route']?$data['route']:'/parent/');
				$pathComponents=removeEmpty($pathComponents);

				// NOTE: I got makeArray() to create a nicely nested assoc array
				// representing the route.ini. I decided to defer the next step of
				// turning it into a working outline-oriented navigation because
				// it was taking too long. For now, simply listing all (qualified) the URLs in a route
				// is good enough. tqii

				// 				$outArray[]=makeArray($pathComponents, $url, $outArray);
				// 				$outArray=removeEmpty($outArray);

				//=======================simple works
			$outString.="<li class='sitemapItem'><a href='http://$url'>$title</a></li>";
				//				$items[$data['route']]="<a href='http://$url'>$title</a>";
				//======================
			}
		}

$outString=$this->translateUrls($outString);
$outString="<ul class='contentzone'>$outString</UL>";
//$outString=$this->htmlList($outArray, false, array('id'=>'siteList'), false);
echo $outString;

?>