<?php
\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'codeNav'),
		array('name'=>'contentArray')
	)));

\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this->contentArray,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'pageFormTemplates.ini')
	)));

$contentArray=$this->contentArray;
$outString='';

//GLOBAL OVERRIDES (from content dir) =========================================================================
global $thiss;
$thiss=$this;
function applyStyle($cssString){
	global $thiss;
	$thiss->headStyle()->appendStyle($cssString);
}

//$this->headStyle()->appendStyle($contentArray['globalItems']['CSS']['main.css']);
array_map('applyStyle', $contentArray['globalItems']['CSS']);

$confirmationTemplate=$this->contentArray['pageFormTemplates.ini']['confirmationPageTemplate'];

$confirmationPageTemplate=\Q\Utils::htmlEntities($confirmationTemplate);

$confirmationPageTemplate=json_encode($confirmationPageTemplate);
$list=$contentArray['products.ini'];

	$json=json_encode($list);
	$outString="<div class='serverData' id='productInfo' style='display:none;'>$json</div>";
	$outString.="<div class='serverData' id='confirmationPageTemplate' style='display:none;'>$confirmationPageTemplate</div>";
	$outString.="<ul style='float:left;border:2pt solid #ccc;margin-left:20px;margin-bottom:40px;padding:20px;text-align:left;'>";

		foreach ($list as $label=>$data){

			$outString.="<ul fieldName='details' style='margin-left:20px;margin-bottom:20px;'>";
			foreach ($data as $label2=>$data2){
				if (gettype($data2)!='array'){
					$outString.="<li fieldName='$label2' style='margin-left:20px;'>$data2</li>";
				}
				else{
					$outString.="<ul fieldName='$label2' style='margin-left:20px;'>";
					foreach ($data2 as $label3=>$data3){
						if (gettype($data3)!='array'){
							$outString.="<li fieldName='$label3' style='padding-left:20px;'>$data3</li>";
						}
						else{
							$outString.="<ul fieldName='$label3' style='margin-left:20px;'>";
							foreach ($data3 as $label4=>$data4){
							$outString.="<li fieldName='$label4' style='padding-left:20px;'>$label4: $data4</li>";
							}
							$outString.="</ul></li>";
						}
					}
					$outString.="</ul></li>";
				}
			}
			$outString.="</ul></li>";
		}

	$outString.="</ul>";

$outString="
<div class='mainContentContainer' style='overflow:hidden;position:relative;'>

<div style='font-size:10pt;color:#999;width:600px;text-align:left;margin-bottom:10pt;'>
	Please note: <b>Javascript</b> is required to use this site.<p/>
	In order to turn Javascript on, go to your
	browser's 'Preferences' (or 'Internet Options' in IE) and
	click on or enable/allow Javascript.
	 Then reload this page. </p>
	Browser-specific details are
	available <a href='http://help.yahoo.com/kb/index?locale=en_US&page=content&y=PROD_MSNG_MSNGIOS&id=SLN1648&impressions=true' style='font-size:100%;color:#A69E8B;text-decoration:underline;'>HERE</a>.
</div>
	$outString
</div>
";


echo $outString;



