<?php
\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'codeNav'),
		array('name'=>'contentArray')
	)));

//INIT =========================================================================


$contentArray=$this->contentArray;



//MAIN CONTENT SECTION =========================================================================

$tabString='';
$panelContentString='';
		$list=$contentArray['panelItems'];
		foreach ($list as $label=>$element){
				
		$id=md5($label);
		$tabLabel=$this->filenameToLabel($label);
		$tabString.="<li class='panelTab'><div class='tabControlGuts'><a class='contentListActivator' id='linkto_$id' href='#$id'>$tabLabel</a></div></li>";


			if (is_array($element)){ //ie, if this is from a .ini that will get processed through a template
			
				$breakout=explode('/', $element['templateName']);
				$container=$breakout[0];
				$filename=$breakout[1];
				if (!isset($contentArray[$container]) || !isset($contentArray[$container][$filename])){
					$elementString="The template {$element['templateName']} is not defined for $label<br/";
				}
				else{ //it is a normal .html file that just needs to be processed into the page
			
					$elementString=\Q\Utils::templateReplace(Array(
						'template'=>$contentArray[$container][$filename],
						'replaceObject'=>$element['data']
					
					));
					// templateReplace($args){
					// 	$template=$args['template'];
					// 	$replaceObject=$args['replaceObject'];
					// 	
					// 	
					// \Q\Utils::templateReplace(array(
					// 	'template'=>$
					// ));
			
				}

				$panelContentString.="<li class='switchablePanel' id='$id'>$elementString</li>";
			}
			else{		
				$panelContentString.="<li class='switchablePanel' id='$id'>$element</li>";
			}

		}
$panelContentString="<ul id='contentList'>$panelContentString</ul>";


$panelString="
<div class='mainContentContainer'>
	<div id='panelContainer'>
		<div id='tabList' style='display:none;'>$tabString</div>
		<div id='tabDisplayContainer' class='sliderTopControls'></div>
		<div class='masterPanelList' style='clear:both;'>
			$panelContentString
		</div>
	</div>
</div>
";

//OUTPUT SECTION =========================================================================


echo $panelString;