<?php
\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'codeNav'),
		array('name'=>'contentArray')
	)));




//DEFAULT STYLES (for this page type) =========================================================================

$styleString="



";


$this->headStyle()->appendStyle($styleString);





//INIT =========================================================================


$contentArray=$this->contentArray;



//MAIN CONTENT SECTION =========================================================================

$tabString='';
$panelContentString='';
		$list=$contentArray['panelItems'];
		foreach ($list as $label=>$element){
			$id=md5($label);
			$tabLabel=$this->filenameToLabel($label);
			$panelContentString.="<li class='switchablePanel' id='$id'>$element</li>";
			$tabString.="<li class='panelTab'><div class='tabControlGuts'><a class='contentListActivator' href='#$id'>$tabLabel</a></div></li>";
		}
$panelContentString="<ul id='contentList'>$panelContentString</ul>";

$headBanner=$contentArray['headBanner.html'];

$panelString="
<div class='mainContentContainer'>
	<div id='panelContainer'>
		<div id='tabList' style='display:none;'>$tabString</div>
		<div id='tabDisplayContainer' class='sliderTopControls'></div>
		<div id='panelList' style='clear:both;'>
			$panelContentString
		</div>
	</div>
</div>
";

//OUTPUT SECTION =========================================================================


echo $panelString;