<?php
\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'codeNav'),
		array('name'=>'contentArray')
	)));

//INIT =========================================================================


$contentArray=$this->contentArray;



//MAIN CONTENT SECTION =========================================================================

$tabString='';
$panelContentString='';
		$list=$contentArray['panelImages'];
		if (is_array($contentArray['parameterFiles'])){
			$parameterFiles=$contentArray['parameterFiles'];
		}
		else{
			$parameterFiles=array();
		}
		if (is_array($contentArray['templates'])){
			$templates=$contentArray['templates'];
		}
		else{
			$templates=array();
		}
		if (isset($contentArray['controlParameters.ini']) && is_array($contentArray['controlParameters.ini'])){
			$controlParameters=$contentArray['controlParameters.ini'];
		}
		else{
			$controlParameters=array();
		}
		
		$showTabs=!isset($controlParameters['showTabs']) ||(isset($controlParameters['showTabs']) && $controlParameters['showTabs']);


		if (isset($controlParameters['tabLabelType'])){
			$tabLabelType=$controlParameters['tabLabelType'];
		}
		else{
			$tabLabelType='';
		}
		$counter=0;
		foreach ($list as $label=>$element){
			$counter++;
			$id=md5($label);
		if ($showTabs){

			switch ($tabLabelType){
				case 'index':
					$tabLabel=$counter;
					break;
				default:
					$tabLabel=$this->filenameToLabel($label);
					break;
			}
			
			$tabString.="<li class='panelTab'><div class='tabControlGuts'><a class='contentListActivator' href='#$id'>$tabLabel</a></div></li>";
		}
		else{
		//figure out how to tell anySlider not to show the tabs		
		}

			$tmp=explode('.', $label);
			$parameterFileName=$tmp[0].'.ini';
	
			if (isset($parameterFiles[$parameterFileName])){
				$parameterFile=$parameterFiles[$parameterFileName];
			}
			elseif (isset($parameterFiles['_default'])){
				$parameterFile=$parameterFiles['_default'];
			}
			else{
				$parameterFile=array();
			}
			
			$parameterFile['imageLink']=$element;
			$parameterFile['imageName']=$label;
			
			preg_match('/[a-zA-Z]+_(.*?)\..*$/', $label, $extractedBits);

			$parameterFile['imageLabel']=$extractedBits[1];
			
			$tmp=explode('_', $parameterFile['imageLabel']);
		
	
			$parameterFile['imageLabelPart1']=isset($tmp[0])?$tmp[0]:'';
			$parameterFile['imageLabePart2']=isset($tmp[1])?$tmp[1]:'';
			$parameterFile['imageLabelPart3']=isset($tmp[2])?$tmp[2]:'';
			$parameterFile['imageLabelPart4']=isset($tmp[3])?$tmp[3]:'';
	

			if (isset($parameterFile['templateName'])){
			
				$templateName=$parameterFile['templateName'];
			}
			else{
				$templateName='templates/_default.html';
			}
			
				$breakout=explode('/', $templateName);
				$container=$breakout[0];
				$fileName=$breakout[1];
		
				if (!isset($contentArray[$container]) || !isset($contentArray[$container][$fileName])){
					$template="<div class='panelItem'><img src='<!imageLink!>'/></div>"; 
				}
				else{
					$template=$contentArray[$container][$fileName];
				}
	
			
			$templateResult=\Q\Utils::templateReplace(Array(
				'template'=>$template,
				'replaceObject'=>$parameterFile
			
			));

			if (isset($contentArray['wrapperTemplate.html'])){
				$wrapperTemplate=$contentArray['wrapperTemplate.html'];
			}
			else{
				$wrapperTemplate="<!templateResult!>";
			}

			$elementString=\Q\Utils::templateReplace(Array(
				'template'=>$wrapperTemplate,
				'replaceObject'=>array('templateResult'=>$templateResult)
			
			));
			
			$panelContentString.="<li class='switchablePanel' id='$id'>$elementString</li>";

		}
$panelContentString="<ul id='contentList'>$panelContentString</ul>";

$headBanner=$contentArray['headBanner.html'];

$panelString="
<div class='mainContentContainer'>
	<div id='panelContainer'>
		<div id='tabList' style='display:none;'>$tabString</div>
		<div id='tabDisplayContainer' class='sliderTopControls'></div>
		<div class='masterPanelList' style='clear:both;'>
			$panelContentString
		</div>
	</div>
</div>
";

//OUTPUT SECTION =========================================================================


echo $panelString;