<?php
\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'codeNav'),
		array('name'=>'contentArray')
	)));



//INIT =========================================================================


$contentArray=$this->contentArray;


//GLOBAL OVERRIDES (from content dir) =========================================================================
global $thiss;
$thiss=$this;
function applyStyle($cssString){
	global $thiss;
	$thiss->headStyle()->appendStyle($cssString);
}

//$this->headStyle()->appendStyle($contentArray['globalItems']['CSS']['main.css']);
array_map('applyStyle', $contentArray['globalItems']['CSS']);

//MAIN CONTENT SECTION =========================================================================

$tabString='';
$panelContentString='';
		$list=$contentArray['panelItems'];
		foreach ($list as $label=>$element){
			$id=md5($label);
			$tabLabel=$this->filenameToLabel($label);
			$panelContentString.="<li class='switchablePanel' id='$id'>$element</li>";
			$tabString.="<li class='panelTab'><div class='tabControlGuts'><a class='contentListActivator' href='#$id'>$tabLabel</a></div></li>";
		}
$panelContentString="<ul id='contentList' style='height:500px;'>$panelContentString</ul>";

$headBanner=$contentArray['headBanner.html'];

$elementList=$contentArray['images'];

foreach ($elementList as $label=>$data){
	$panelContentString=str_replace("../images/$label", $data, $panelContentString);
	$headBanner=str_replace("images/$label", $data, $headBanner);
}

$panelString="
<div class='mainContentContainer'>
	<div id='feature'>
		<div id='featureHeadline'>{$contentArray['featureHeadline.html']}</div>
		<div id='featureBodyText'>{$contentArray['featureBodyText.html']}</div>
	</div>
	<div id='panelContainer'>
		<div id='tabList' style='display:none;'>$tabString</div>
		<div id='tabDisplayContainer' class='sliderTopControls'></div>
		<div id='panelList' style='clear:both;'>
			$panelContentString
		</div>
	</div>
</div>
";

$this->headStyle()->appendStyle("
.contentListActivator{color:#ddeeff;background:#588599;}
.contentListActivator:hover{color:blue;background:#ddeeff;}
#tabContainer{clear:both;border-bottom:2pt solid gray;height:20px;}
.panelTab{float:left;margin-right:5px;list-style-type: none; padding-left:5px;padding-right:5px;}
#feature{float:left;width:250px;margin-left:60px;margin-top:20px;}
#featureHeadline{font-weight:bold;font-size:150%;margin-bottom:20px;}
#panelContainer{float:left;width:560px;margin-left:50px;margin-top:20px;overflow:hidden;}
#panelList li {margin-bottom:10px;}
");

//OUTPUT SECTION =========================================================================


echo $panelString;