<?php
\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'codeNav'),
		array('name'=>'contentArray')
	)));



//INIT =========================================================================


$contentArray=$this->contentArray;

if (isset($contentArray['pageTitle.txt'])){
	$this->headTitle($contentArray['pageTitle.txt']);
}
else{
	$request = Zend_Controller_Front::getInstance()->getRequest();
	$this->headTitle($request->getActionName().'/')
		 ->headTitle($request->getControllerName());
}

//DROPDOWN MENU =========================================================================

$dropdownStyles="

	/*
		LEVEL ONE
	*/
	ul.dropdown                         { position: relative; float:right; z-index:1000;}
	ul.dropdown li                      { float: left; zoom: 1; }
	ul.dropdown a:hover		            { color: #000; }
	ul.dropdown a:active                { color: #ffa500; }
	ul.dropdown li a                    { display: block; padding: 4px 8px; border-right: 1px solid #333;
										  color: #222; text-decoration:none; }
	ul.dropdown li:last-child a         { border-right: none; } /* Doesn't work in IE */
	ul.dropdown li.hover,
	ul.dropdown li:hover                { background: #F3D673; color: black; position: relative; }
	ul.dropdown li.hover a              { color: black; }


	/*
		LEVEL TWO
	*/
	ul.dropdown ul 						{ width: 220px; visibility: hidden; position: absolute; top: 100%; left: 0; }
	ul.dropdown ul li 					{ font-weight: normal; background: #f6f6f6; color: #000;
										  border-bottom: 1px solid #ccc; float: none; }

										/* IE 6 & 7 Needs Inline Block */
	ul.dropdown ul li a					{ border-right: none; width: 100%; display: inline-block; }

	/*
		LEVEL THREE
	*/
	ul.dropdown ul ul 					{ left: 100%; top: 0; }
	ul.dropdown li:hover > ul 			{ visibility: visible; }
";

$ieStyle="ul.dropdown ul li					{ display: inline; width: 100%; } ";

$dropdownScript="
$(function(){
    $('ul.dropdown li').hover(function(){

        $(this).addClass('hover');
        $('ul:first',this).css('visibility', 'visible');

    }, function(){

        $(this).removeClass('hover');
        $('ul:first',this).css('visibility', 'hidden');

    });

    $('ul.dropdown li ul li:has(ul)').find('a:first').append(' &raquo; ');

});
";

$this->headScript()->appendScript($dropdownScript); //inlineScript() DOES NOT WORK. The code is never expressed.

$this->headStyle()->appendStyle($dropdownStyles);
$this->headStyle()->appendStyle($ieStyle, array('conditional'=>"lte IE 7"));



$controlsString=$this->unorderedListForSelect(
	$contentArray['headNav.ini']['menu'],
	array('mainClass'=>'dropdown')
);

$controlsString=$this->translateUrls($controlsString);

$controlsString="
<div style='width:1000px;background:#def;height:50px;margin:0px 0px 20px 0px;'>
	<div style='width:860px;padding-top:20px;margin:0px 70px 20px 70px;'>$controlsString</div>
</div>";

//GLOBAL OVERRIDES (from content dir) =========================================================================
global $thiss;
$thiss=$this;
function applyStyle($cssString){
	global $thiss;
	$thiss->headStyle()->appendStyle($cssString);
}

//$this->headStyle()->appendStyle($contentArray['globalItems']['CSS']['main.css']);
array_map('applyStyle', $contentArray['globalItems']['CSS']);

//MAIN CONTENT SECTION =========================================================================

$tabString='';
$panelContentString='';
		$list=$contentArray['panelItems'];
		foreach ($list as $label=>$element){
			$panelContentString.="<li id='$label'>$element</li>";
			$tabString.="<li class='panelTab'><a href='#$label'>$label</a></li>";
		}
$panelContentString="<ul id='panelItems'>$panelContentString</ul>";

$headBanner=$contentArray['headBanner.html'];

$elementList=$contentArray['images'];

foreach ($elementList as $label=>$data){
	$panelContentString=str_replace("../images/$label", $data, $panelContentString);
	$headBanner=str_replace("images/$label", $data, $headBanner);
}

$panelString="
<div>
	<div id='feature'>
		<div id='featureHeadline'>{$contentArray['featureHeadline.html']}</div>
		<div id='featureBodyText'>{$contentArray['featureBodyText.html']}</div>
	</div>
	<div id='panelContainer'>
		<div id='tabContainer' style=''>$tabString</div>
		<div id='panelList' style='clear:both;'>
			$panelContentString
		</div>
	</div>
</div>
";

$this->headStyle()->appendStyle("
#tabContainer{clear:both;border-bottom:2pt solid gray;height:20px;}
.panelTab{float:left;margin-right:5px;list-style-type: none;}
#feature{float:left;width:250px;margin-left:60px;margin-top:20px;}
#featureHeadline{font-weight:bold;font-size:150%;margin-bottom:20px;}
#panelContainer{float:left;width:560px;margin-left:50px;margin-top:20px;overflow:hidden;border:1pt solid gray;}
#panelList li {border-bottom:1pt solid gray;margin-bottom:10px;}
");

//OUTPUT SECTION =========================================================================

echo $headBanner;
echo $controlsString;
echo $panelString;