<?php
\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'codeNav'),
		array('name'=>'contentArray')
	)));




//DEFAULT STYLES (for this page type) =========================================================================

$styleString="

.mainContentContainer{
	width:900px;
	height:500px;
	font-size:14pt;
	overflow:hidden;
	text-align:left;
	height:100%;
}

.panelItemContainer{
	font-size:10pt;
	position:relative;
}

.panelHeadline{
	font-size:24pt;
	margin-bottom:20px;
}
.panelSimpleBodyText{
	margin:0px 10px;
}

.panelBasicImage{
}

#panelItemContainer{
	width:500px;
}

.contentListActivator{color:#ddeeff;background:#588599;}
.contentListActivator:hover{color:blue;background:#ddeeff;}

#tabContainer{clear:both;border-bottom:2pt solid gray;height:20px;}

.panelTab{
}

#feature{
	float:left;width:265px;
	margin-top:20px;
	overflow:hidden;
	font-size:10pt;
}
#featureHeadline{font-weight:bold;font-size:120%;margin-bottom:20px;}

#panelContainer{float:left;width:620px;
margin-left:13px; /*the boundary between left column and panel*/
margin-top:20px;overflow:hidden;}

#contentList{
}



/*PANEL APPEARANCE =========================================*/

.anythingSlider-default.activeSlider .anythingControls a{
	color:#ccc !important;
}
.anythingSlider-default.activeSlider .anythingWindow {
	border-color: transparent !important;
	border-bottom:none !important;
}

/*TAB PANEL CONTROLS =========================================*/

#panelList{
	border:4pt solid #e6e3e3;
	border-radius: 10px 10px 10px 10px;
	-moz-border-radius: 10px 10px 10px 10px;
	-webkit-border-radius: 10px 10px 10px 10px;
	width:610px;
	height:448px;
}

#panelList ul {
width:610px;
height:448px;
}

.sliderTopControls{
	padding-left:0px;
}

.sliderTopControls li{
	display:inline;
	margin:0px 3px 0px 3px;
	padding:0px 20px;
	background: #e6e3e3;
	border-radius: 2px 2px 2px 2px;
	-moz-border-radius: 2px 2px 2px 2px;
	-webkit-border-radius: 2px 2px 2px 2px;

	-moz-box-shadow: inset -2px -2px 2px #888;
	-webkit-box-shadow: inset -2px -2px 2px #888;
	box-shadow: inset -2px -2px 2px #888;


}

.tabControlGuts{
padding:10px 0px;
}
.sliderTopControls a {
	/* top shadow */
	color: #2a7fff;
	font-size:8pt;
	vertical-align:top;
}

.sliderTopControls a:hover{
color:#888;
}

.thumbNav{
line-height:30px;
}


.anythingSlider-default .arrow a {

background: url(/js/widgets/stylesheets/anythingslider/imagesCustom/defaultXLighter.png) no-repeat;
}

";


$this->headStyle()->appendStyle($styleString);





//INIT =========================================================================


$contentArray=$this->contentArray;



//MAIN CONTENT SECTION =========================================================================

$tabString='';
$panelContentString='';
		$list=$contentArray['panelItems'];
		foreach ($list as $label=>$element){
			$id=md5($label);
			$tabLabel=$this->filenameToLabel($label);
			$panelContentString.="<li class='switchablePanel' id='$id'>$element</li>";
			$tabString.="<li class='panelTab'><div class='tabControlGuts'><a class='contentListActivator' href='#$id'>$tabLabel</a></div></li>";
		}
$panelContentString="<ul id='contentList'>$panelContentString</ul>";

$headBanner=$contentArray['headBanner.html'];

$panelString="
<div class='mainContentContainer'>
	<div id='feature'>
		{$contentArray['feature.html']}
	</div>
	<div id='panelContainer'>
		<div id='tabList' style='display:none;'>$tabString</div>
		<div id='tabDisplayContainer' class='sliderTopControls'></div>
		<div id='panelList' style='clear:both;'>
			$panelContentString
		</div>
	</div>
</div>
";

//OUTPUT SECTION =========================================================================


echo $panelString;