<?php
$featurePanels=isset($this->contentArray['featurePanels'])?$this->contentArray['featurePanels']:'';
$infoPanels=isset($this->contentArray['infoPanels'])?$this->contentArray['infoPanels']:'';
$specs=array();

if ($featurePanels){
$scrollFeature=$this->prepareSlickScroller($featurePanels, 'scroll1Container');
$scrollFeature="
<div id='introduction' class='genericScrollContainer'>
	$scrollFeature
</div>
";
}
else{
	$scrollFeature='';
}


if (count($infoPanels)){
	$infoPanels['!_feature']=$scrollFeature;
	ksort($infoPanels);
	$infoString=$this->prepareSlickScroller($infoPanels, 'info1Container');
}
else{
$infoString=$scrollFeature;
}


// if (!$this->endOfBodyHtml){ $this->endOfBodyHtml='';}
// $joyrideFeature=$this->fabricateJoyrideList($infoPanels);
// $this->endOfBodyHtml.=$joyrideFeature;

//$this->javascriptCalls('slick.js', "js/vendor/node_modules/slick-carousel/slick/");

$this->javascriptCalls('slickCarousel.js', "/js/fidgets/controls/slickCarousel/");
$this->javascriptCalls('contactForm.js', "/js/fidgets/controls/contactForm/");
$this->javascriptCalls('verticalStructure.js', "/js/fidgets/controls/verticalStructure/");
$this->javascriptCalls('featureOverlay.js', "/js/fidgets/controls/featureOverlay/");

$this->headLink()->appendStylesheet('js/vendor/node_modules/slick-carousel/slick/slick.css');
$this->headLink()->appendStylesheet('js/vendor/node_modules/slick-carousel/slick/slick-theme.css');

//$this->javascriptCalls('setDefaultLibrary', "js/foundation/");


echo "

	$infoString

";
