<?php
\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'codeNav'),
		array('name'=>'contentArray')
	)));



//INIT =========================================================================
$styleString="

.mainContentContainer{
	width:900px;
	font-size:14pt;
	overflow:hidden;
	text-align:left;
}

.panelItemContainer{
	font-size:10pt;
	position:relative;
}

.panelHeadline{
	font-size:24pt;margin-bottom:20px;
}
.panelSimpleBodyText{
	margin:0px 10px;
}

.panelBasicImage{
}

#panelItemContainer{
	width:500px;
}

.contentListActivator{color:#ddeeff;background:#588599;}
.contentListActivator:hover{color:blue;background:#ddeeff;}

#tabContainer{clear:both;border-bottom:2pt solid gray;height:20px;}

.panelTab{
}

#feature{
	float:left;width:265px;
	margin-top:20px;
	overflow:hidden;
	font-size:10pt;
}
#featureHeadline{font-weight:bold;font-size:120%;margin-bottom:20px;}

#panelContainer{float:left;width:620px;
margin-left:13px; /*the boundary between left column and panel*/
margin-top:20px;overflow:hidden;}

#contentList{
}
";

$this->headStyle()->appendStyle($styleString);

$contentArray=$this->contentArray;

//DROPDOWN MENU =========================================================================

$dropdownStyles="

	/*
		LEVEL ONE
	*/
	ul.dropdown                         { position: relative; float:right; z-index:1000;}
	ul.dropdown li                      { float: left; zoom: 1; }
	ul.dropdown a:hover		            { color: #000; }
	ul.dropdown a:active                { color: #ffa500; }
	ul.dropdown li a                    { display: block; padding: 4px 8px; border-right: 1px solid #333;
										  color: #222; text-decoration:none; }
	ul.dropdown li:last-child a         { border-right: none; } /* Doesn't work in IE */
	ul.dropdown li.hover,
	ul.dropdown li:hover                { background: #F3D673; color: black; position: relative; }
	ul.dropdown li.hover a              { color: black; }


	/*
		LEVEL TWO
	*/
	ul.dropdown ul 						{ width: 220px; visibility: hidden; position: absolute; top: 100%; left: 0; }
	ul.dropdown ul li 					{ font-weight: normal; background: #f6f6f6; color: #000;
										  border-bottom: 1px solid #ccc; float: none; }

										/* IE 6 & 7 Needs Inline Block */
	ul.dropdown ul li a					{ border-right: none; width: 100%; display: inline-block; }

	/*
		LEVEL THREE
	*/
	ul.dropdown ul ul 					{ left: 100%; top: 0; }
	ul.dropdown li:hover > ul 			{ visibility: visible; }
";

$ieStyle="ul.dropdown ul li					{ display: inline; width: 100%; } ";

$dropdownScript="
$(function(){
    $('ul.dropdown li').hover(function(){

        $(this).addClass('hover');
        $('ul:first',this).css('visibility', 'visible');

    }, function(){

        $(this).removeClass('hover');
        $('ul:first',this).css('visibility', 'hidden');

    });

    $('ul.dropdown li ul li:has(ul)').find('a:first').append(' &raquo; ');

});
";

$this->headScript()->appendScript($dropdownScript); //inlineScript() DOES NOT WORK. The code is never expressed.

$this->headStyle()->appendStyle($dropdownStyles);
$this->headStyle()->appendStyle($ieStyle, array('conditional'=>"lte IE 7"));



//GLOBAL OVERRIDES (from content dir) =========================================================================
global $thiss;
$thiss=$this;
function applyStyle($cssString){
	global $thiss;
	$thiss->headStyle()->appendStyle($cssString);
}

//$this->headStyle()->appendStyle($contentArray['globalItems']['CSS']['main.css']);
array_map('applyStyle', $contentArray['globalItems']['CSS']);





$contentPanel=$contentArray['contentPanel.html'];
$elementList=$contentArray['elements'];

if (is_array($elementList)){
	foreach ($elementList as $label=>$data){
		$contentPanel=str_replace("elements/$label", $data, $contentPanel);
	}
}

//OUTPUT SECTION =========================================================================

$outString="
<div class='mainContentContainer'>
		$contentPanel
</div>
";
?>

<?php  echo $outString;?>
