<?php
\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'codeNav'),
		array('name'=>'contentArray')
	)));



//INIT =========================================================================
$styleString="

.mainContentContainer{
	width:900px;
	font-size:14pt;
	overflow:hidden;
	text-align:left;
}

";

// DISCARD THIS AFTER VERIFYING THAT NO PAGES USE IT =====================
// 
// .panelItemContainer{
// 	font-size:10pt;
// 	position:relative;
// }
// 
// .panelHeadline{
// 	font-size:24pt;margin-bottom:20px;
// }
// .panelSimpleBodyText{
// 	margin:0px 10px;
// }
// 
// .panelBasicImage{
// }
// 
// #panelItemContainer{
// 	width:500px;
// }
// 
// .contentListActivator{color:#ddeeff;background:#588599;}
// .contentListActivator:hover{color:blue;background:#ddeeff;}
// 
// #tabContainer{clear:both;border-bottom:2pt solid gray;height:20px;}
// 
// .panelTab{
// }
// 
// #feature{
// 	float:left;width:265px;
// 	margin-top:20px;
// 	overflow:hidden;
// 	font-size:10pt;
// }
// #featureHeadline{font-weight:bold;font-size:120%;margin-bottom:20px;}
// 
// #panelContainer{float:left;width:620px;
// margin-left:13px; /*the boundary between left column and panel*/
// margin-top:20px;overflow:hidden;}
// 
// #contentList{
// }
// =============================================================================

$this->headStyle()->appendStyle($styleString);

$contentArray=$this->contentArray;

//GLOBAL OVERRIDES (from content dir) =========================================================================
global $thiss;
$thiss=$this;
function applyStyle($cssString){
	global $thiss;
	$thiss->headStyle()->appendStyle($cssString);
}

//$this->headStyle()->appendStyle($contentArray['globalItems']['CSS']['main.css']);
array_map('applyStyle', $contentArray['globalItems']['CSS']);


$contentPanel=$contentArray['contentPanel.html'];


//OUTPUT SECTION =========================================================================

$outString="
<div class='mainContentContainer pureHtmlIntoLayout'>
		$contentPanel
</div>
";
?>

<?php  

echo $outString;?>
