<?php
\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'codeNav'),
		array('name'=>'contentArray')
	)));



//INIT =========================================================================
$styleString="

.mainContentContainer{
	width:1000px;
	font-size:14pt;
	overflow:hidden;
	text-align:left;
}

";

$this->headStyle()->appendStyle($styleString);

$contentArray=$this->contentArray;

//GLOBAL OVERRIDES (from content dir) =========================================================================
global $thiss;
$thiss=$this;
function applyStyle($cssString){
	global $thiss;
	$thiss->headStyle()->appendStyle($cssString);
}

//$this->headStyle()->appendStyle($contentArray['globalItems']['CSS']['main.css']);
array_map('applyStyle', $contentArray['globalItems']['CSS']);


$contentPanel=$contentArray['contentPanel.html'];


//OUTPUT SECTION =========================================================================

$outString="
<div class='mainContentContainer pureHtmlIntoLayout'>
		$contentPanel
</div>
";
?>

<?php  

echo $outString;?>
