<?php


// templates in the ./layout directory, peer to ./layout/default 
// are referenced by the controllers in application/controllers
// not the multiSite modules.


$serverComm=$this->serverComm;

$headTitle=$this->headTitle();
$headStyle=$this->headStyle();

$viewContent=$this->layout()->content;

$javascript=$this->headScript(); //note: call for steal.js is literal so it always executes first, others can count on it

$route=Zend_Controller_Front::getInstance()->getRouter()->getCurrentRoute()->getDefaults();
if (isset($route['title'])){
	$this->headTitle($route['title']);
}
else{
	$request = Zend_Controller_Front::getInstance()->getRequest();
	$this->headTitle($request->getActionName().'/')
		 ->headTitle($request->getControllerName());
}

$jqueryReadyScript=$this->buildJqueryReadyCall($this->jqueryReadyScript);


$contactFooter=$this->render('default/contactFooter.phtml');

$footer="
<div class='footerContainer'>
	<div class='footerContactBlock'>
		$contactFooter
	</div>
</div>
";

if (APPLICATION_ENV=='production'){
	$widgetScriptCall="<script type='text/javascript' src='/js/steal/steal.production.js?widgets'></script>";
}
else{
	$widgetScriptCall="<script type='text/javascript' src='/js/steal/steal.js?widgets'></script>";
}

if (APPLICATION_ENV=='production' && isset($this->contentArray['analytics.js']) && $this->contentArray['analytics.js']){
	$analyticsString="<script type='text/javascript'>
		{$this->contentArray['analytics.js']}
		</script>";
}
else{
	$analyticsString='';
}

//GLOBAL OVERRIDES (from content dir) =========================================================================

$this->applyStyles($this, $this->contentArray);

	
	if (isset($this->contentArray['superGlobalItems']['COMPONENTS']['headSection.html'])){
		$superGlobalHeadStuff=$this->contentArray['superGlobalItems']['COMPONENTS']['headSection.html'];
	}
	else{
		$superGlobalHeadStuff='';
	}
	if (isset($this->contentArray['globalItems']['COMPONENTS']['headSection.html'])){
		$siteHeadStuff=$this->contentArray['globalItems']['COMPONENTS']['headSection.html'];
	}
	else{
		$siteHeadStuff='';
	}

//MAIN CONTENT SECTION =========================================================================
/*
font-family: 'Satisfy', cursive;
font-family: 'Open Sans', sans-serif;
font-family: 'Open Sans Condensed', sans-serif;
*/
$outputString="
	<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01//EN'
	   'http://www.w3.org/TR/html4/strict.dtd'>
	<html>

	<head>
	<META HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=UTF-8'>
	<link href='http://fonts.googleapis.com/css?family=Satisfy|Open+Sans:400italic,400,700|Open+Sans+Condensed:700' rel='stylesheet' type='text/css'>
	<link rel='stylesheet' type='text/css' href='http://yui.yahooapis.com/3.6.0/build/cssreset/cssreset-min.css'>
	<link rel='stylesheet' type='text/css' href='/css/baseCss/foundation.css'>

	$headTitle

	<style type='text/css'><!--
		a {text-decoration:none;}
	--></style>

	$headStyle

	
	$superGlobalHeadStuff
	
	$siteHeadStuff
	
	</head>

	<body >
	<table width=100%><tr><td align=center>
	$serverComm

	$viewContent

	$footer

	</body>

	$javascript

	</table>
	$widgetScriptCall
	$jqueryReadyScript
	$analyticsString
	</html>
";

$outputString=$this->translateUrls($outputString);


if (isset($this->contentArray['MACROS'])){
	$outputString=$this->applyMacros($this->contentArray['MACROS'], $outputString); //apply page level macros
}

if (isset($this->contentArray["globalItems"]['MACROS'])){
$outputString=$this->applyMacros($this->contentArray["globalItems"]['MACROS'], $outputString);
}

if (isset($this->contentArray["superGlobalItems"]['MACROS'])){
$outputString=$this->applyMacros($this->contentArray["superGlobalItems"]['MACROS'], $outputString);
}

$outputString=$this->mapServableToHash($this->contentArray, $outputString);
echo $outputString;