<?php 

$bookmark=$this->bookmark;
$outString='';

$outString.="

<div style='margin:15px;border:1pt solid red;padding:25px;width:400px;font-family:sans-serif;font-size:8pt;'>

<div style='float:left;'>
<div style='font-weight:bold;margin-bottom:10px;'>status: {$this->bookmark['status']}</div>
<div style='margin-bottom:10px;'>target URI= <a href='{$this->bookmark['uri']}'>{$this->bookmark['uri']}</a></div>
<div style='margin-bottom:10px;'><a href='http://<!rootDomainSegment!>?{$bookmark['shortId']}'>http://<!rootDomainSegment!>?{$bookmark['shortId']}</a></div>
</div>

<div style='float:right;border:1pt solid gray; height:55px;width:190px;'>

</div>

<textarea style='height:150px;width:400px;padding-left:25px;'>




{$bookmark['anchor']}

http://<!rootDomainSegment!>?{$bookmark['shortId']}

</textarea>

</div>

";

echo $this->translateUrls($outString);