<?php

$uri=isset($this->parms['uri'])?$this->parms['uri']:'';
$anchor=isset($this->parms['anchor'])?$this->parms['anchor']:'';


$outString="	<div style='font-family:sans-serif;height:100px;width:300px;background:#afa;padding:50px 0px 25px 0px;'>
	<form>
	<table>
		<tr><td>URI:</td><td><input name='uri' value='{$uri}'></td></tr>
		<tr><td>Anchor:</td><td><input name='anchor' value='{$anchor}'></td></tr>
		<tr><td colspan='2'><input type='submit'>
		</form>
	</div>
";

echo $outString;