<?php

$outString="
<div style='font-family:sans-serif;padding:50px;width:400px;'>

<div>

The only way to use Q Shortener is with a bookmarklet.<br/><br/>
Drag the button below, 'tq-', to your bookmark bar and click to your heart's content.

</div>

<div style='margin:70px 40px 70px 100px;'>
<a style='padding:5px;border:1pt solid green;
  -moz-border-radius: 4px; /* Firefox */
  -webkit-border-radius: 4px; /* Safari, Chrome */
  border-radius: 4px; /* CSS3 */
	-webkit-box-shadow:2px 3px 5px rgba(0, 0, 0, .5);
	   -moz-box-shadow:2px 3px 5px rgba(0, 0, 0, .5);
	        box-shadow:2px 3px 5px rgba(0, 0, 0, .5);
'
href=\"javascript:(function()%7Bvar%20bookmarkUrl%3D%28%27http%3A//tqwhite.org%3Furi%3D%27+window.location.href+%27%26anchor%3D%27+escape%28document.title%29%29%3Bwindow.open%28bookmarkUrl%2C%20%27TQs%20Short%20URLs%27%2C%20%27height%3D330%2C%20width%3D495%27%29%3B%7D)();\"
>
tq-
</a>
</div>


<div style='margin-bottom:20px;'>

You can use the following code to customize your own.

</div>

<div style='width:500px;color:gray;'>
javascript:(function(){var bookmarkUrl=('http://tqwhite.org?uri='+window.location.href+'&anchor='+escape(document.title));window.open(bookmarkUrl, 'TQs Short URLs', 'height=330, width=495');})();
</div>

</div>
";

echo $outString;