<?php

\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'codeNav'),
		array('name'=>'contentArray')
	)));

//INIT =========================================================================


$contentArray=$this->contentArray; //needs to be a property so helpers can see it




//DEFAULT STYLES (for this page type) =========================================================================

$styleString="
.panelContainer{
	width:800px;
	font-size:10pt;
}
.panelHeadline{
font-size:24pt;margin-bottom:20px;
}
.panelSimpleBodyText{
	margin:0px 10px;
}
.panelBasicImage{
	width:750px;
	margin:0px 25px;
}
.anythingSlider-default .arrow a {

background: url(/js/widgets/stylesheets/anythingslider/imagesCustom/defaultX.png) no-repeat;
}




";

$this->headStyle()->appendStyle($styleString);

//GLOBAL OVERRIDES (from content dir) =========================================================================
global $thiss;
$thiss=$this;
function applyStyle($cssString){
	global $thiss;
	$thiss->headStyle()->appendStyle($cssString);
}

//$this->headStyle()->appendStyle($contentArray['globalItems']['CSS']['main.css']);
array_map('applyStyle', $contentArray['globalItems']['CSS']);

//MAIN CONTENT SECTION =========================================================================

$panelContentString='';
		$list=$this->contentArray['slideshow'];
		foreach ($list as $label=>$element){
			$panelContentString.="<li>$element</li>";
		}
$panelContentString="<ul id='anythingslider' class='mainContentContainer panelBlock'>$panelContentString</ul>";


$elementList=$contentArray['images'];

foreach ($elementList as $label=>$data){
	$panelContentString=str_replace("../images/$label", $data, $panelContentString);
}

$panelString="
$panelContentString
";


//OUTPUT SECTION =========================================================================

echo $panelString;
