<?php

\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'codeNav'),
		array('name'=>'contentArray')
	)));

//INIT =========================================================================


$contentArray=$this->contentArray; //needs to be a property so helpers can see it

if (isset($contentArray['pageTitle.txt'])){
	$this->headTitle($contentArray['pageTitle.txt']);
}
else{
	$request = Zend_Controller_Front::getInstance()->getRequest();
	$this->headTitle($request->getActionName().'/')
		 ->headTitle($request->getControllerName());
}



//GLOBAL OVERRIDES (from content dir) =========================================================================
global $thiss;
$thiss=$this;
function applyStyle($cssString){
	global $thiss;
	$thiss->headStyle()->appendStyle($cssString);
}

//$this->headStyle()->appendStyle($contentArray['globalItems']['CSS']['main.css']);
array_map('applyStyle', $contentArray['globalItems']['CSS']);

//MAIN CONTENT SECTION =========================================================================

$panelContentString='';
		$list=$this->contentArray['slideshow'];
		foreach ($list as $label=>$element){
			$panelContentString.="<li>$element</li>";
		}
$panelContentString="<ul id='anythingslider' class='multiPanelContainer panelBlock'>$panelContentString</ul>";


$elementList=$contentArray['images'];

foreach ($elementList as $label=>$data){
	$panelContentString=str_replace("../images/$label", $data, $panelContentString);
}

$panelString="
$panelContentString
";


//OUTPUT SECTION =========================================================================

echo $panelString;
