<?php
\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'codeNav'),
		array('name'=>'contentArray'),
		array('name'=>'simpleStore')
	)));

$contentArray=$this->contentArray;
$displayTemplates=$this->contentArray['catalogDisplayTemplates'];

$productSectionArray=$this->productSectionArray;

$transformations=array();

$transformations['dollarPrice']=function($itemRec, $referenceDataTagList){$out=isset($itemRec['price'])?'$'.number_format($itemRec['price'], 2):"!isset(\$itemRec['price'])"; return $out;};
$transformations['capsName']=function($itemRec, $referenceDataTagList){$out=isset($itemRec['name'])?strtoupper($itemRec['name']):"!isset(\$itemRec['name'])"; return $out;};
$transformations['catCaps']=function($itemRec, $referenceDataTagList){$out=isset($itemRec['categoryInfo:name'])?strtoupper($itemRec['categoryInfo:name']):"!isset(\$itemRec['categoryInfo:name'])"; return $out;};


if (isset($displayTemplates['transformations.php'])){
	$forbiddenCount=0;
	$forbiddenList=array('exec', 'mysql');
	$displayTemplates['transformations.php']=str_replace($forbiddenList, "", $displayTemplates['transformations.php'], $forbiddenCount);

	if ($forbiddenCount===0){
		eval($displayTemplates['transformations.php']);
	}
	else{
		die("Illegal php statements in transformations file");
	}
}

$referenceData=array();
$outString='';

foreach ($productSectionArray as $label=>$productSection){
		$fileName=str_replace(' ', '_', $label);
		
	if (isset($contentArray['categoryTemplates']) && isset($contentArray['categoryTemplates'][$fileName.'.html'])){

		$blockTemplate=$contentArray['categoryTemplates'][$fileName.'.html'];
	}
	else{
		$blockTemplate=$contentArray['categoryTemplates']['categoryDefaultTemplate.html'];
	}

	$itemProcessResult=$this->processTemplateArray(array(
		'sourceData'=>$productSection,
		'itemTemplate'=>$displayTemplates['productListingTemplate.html'],
		'blockTemplate'=>$blockTemplate,
		'transformations'=>$transformations,
		'referenceData'=>array('categoryInfo'=>array('name'=>$label))
	
	));

	$outString.=$itemProcessResult['outString'];
}



if (isset($displayTemplates['catalogTemplate.html'])){
	$catalogTemplate=$displayTemplates['catalogTemplate.html'];
}
else{
	$catalogTemplate="<!catalogInfo!>";
}

	$catalogProcessResult=$this->processTemplateArray(array(
		'sourceData'=>array(array('catalogInfo'=>$outString)),
		'itemTemplate'=>$catalogTemplate,
		'transformations'=>$transformations
	
	));
	
	$outString=$catalogProcessResult['outString'];


$pageFormTemplates=$this->contentArray['pageFormTemplates'];
$pageFormTemplates=\Q\Utils::htmlEntities($pageFormTemplates);
$pageFormTemplates=json_encode($pageFormTemplates);

$simpleStore=$this->simpleStore;
$simpleStore=\Q\Utils::htmlEntities($simpleStore);
$simpleStore=json_encode($simpleStore);


$outString="
<div class='serverData' id='pageFormTemplates' style='display:none;'>$pageFormTemplates</div>
<div class='serverData' id='simpleStore' style='display:none;'>$simpleStore</div>

<div class='mainContentContainer' style='overflow:hidden;position:relative;'>

	$outString
</div>
";

echo $outString;