<?php
if (isset($this->contentArray['contactFooter.html']) && ''!=$this->contentArray['contactFooter.html']){
	echo $this->contentArray['contactFooter.html'];
}
else{
	echo "
		<div style='width:1000px;text-align:center;font-size:10pt;margin-top:25px;border-top:1pt solid gray;padding-bottom:10px;padding-top:10px;margin-top:10px;'>
			MultiSite by TQ White II &bull; <a href='https://github.com/tqwhite/multiSite'>https://github.com/tqwhite/multiSite</a>

	";
}

?>