<?php

if (APPLICATION_ENV == 'production' && isset($this->contentArray['analytics.js']) && $this->contentArray['analytics.js']) {
	$analyticsString = "<script type='text/javascript'>{$this->contentArray['analytics.js']}</script>";
} else {
	$analyticsString = '';
}

$headStyle = $this->headStyle();
$route = Zend_Controller_Front::getInstance()->getRouter()->getCurrentRoute()->getDefaults();

$title = $this->headTitle();
if (isset($route['title'])) {
	$title = "<TITLE>{$route['title']}</TITLE>";
}

$this->applyStyles($this, $this->contentArray, array('skipSuperGlobal' => true));

$headStyle = $this->headStyle();
$styleLinks = $this->headLink();
$javascript = $this->headScript();
$contentArray = $this->contentArray;
$viewContent = $this->layout()->content;

$headNav = $this->render('default/foundationComponents/base-head-nav.phtml');



//JAVASCRIPT LIBRARY AND SOFTWARE =========================================================================

$this->javascriptCalls('jquery_downloads/jquerypp.custom', "js/vendor/");
$this->javascriptCalls('modernizr.js', "js/vendor/");
$this->javascriptCalls('node_modules/withinviewport/withinviewport.js', "js/vendor/");
$this->javascriptCalls('jquery_downloads/jquery-bullseye-1-0b/jquery.bullseye-1.0.js', "js/vendor/");

$requirejsTemplate = array('itemTemplate' => "'<!filePath!>', ", 'cleanupRegEx' => "/, $/", 'wrapper' => "require([<!itemString!>], initFunction);");
$jsLibAndInit = $this->javascriptCalls('emitJavascript', $requirejsTemplate);

$userJavascript = $this->buildJqueryReadyCall($this->contentArray, 'noScriptTag');


//PARAMETERS (for JS fidgets) =========================================================================

	$serverComm=(isset($this->serverComm))?$this->serverComm:'';
	



$serverData=$this->formatServerData($this->contentArray);
					
if (!$this->endOfBodyHtml){ $this->endOfBodyHtml='';}
if (isset($contentArray['COMPONENTS']) && isset($contentArray['COMPONENTS']['endOfBodyHtml.html']) && $contentArray['COMPONENTS']['endOfBodyHtml.html']){
$this->endOfBodyHtml.=$contentArray['COMPONENTS']['endOfBodyHtml.html'];
}



$outputString = "<!doctype html>
<html class='no-js' lang='en'>
  <head>
    <meta charset='utf-8' />
    <meta name='viewport' content='width=device-width, initial-scale=1.0' />
    $title
	
	<style>html{font-size:62.5%;}</style>
    <link rel='stylesheet' type='text/css' href='css/animate.css/animate.css'/>
    <link rel='stylesheet' href='css/foundation.css' />
	$styleLinks
	
    $headStyle

  </head>
  <body>   

<!-- CONTENT SECTION ================================================== --> 
$viewContent  
<!-- NAVIGATION SECTION ================================================== --> 
$headNav
<!-- DATA SECTION ================================================== --> 
$serverComm
$serverData
{$this->endOfBodyHtml}
<!-- SCRIPT SECTION ================================================== -->    
    
    <script src='js/require.js'></script>
	
    <script type='text/javascript'>
		/* <![CDATA[ */

		requirejs.config({
			paths: {
				jquery: 'js/vendor/jquery',
    			foundation: 'js/vendor/foundation/foundation.min',
    			can:'js/vendor/canjs/can/amd-dev/can'
			}
		});
		
		require(['jquery', 'foundation', 'can'], function(){
				//this calls initFunction() below as callback
				$jsLibAndInit
			});

		var initFunction=function(){
				$(document).foundation();
				$userJavascript
			};	
		

		/* ]]> */
	</script>
  </body>
</html>";

$outputString = $this->translateUrls($outputString);
$outputString = $this->applyAllMacros($this->contentArray, $outputString);
$outputString = $this->mapServableToHash($this->contentArray, $outputString);

echo $outputString;
