<?php

if (APPLICATION_ENV=='production' && isset($this->contentArray['analytics.js']) && $this->contentArray['analytics.js']){
	$analyticsString="<script type='text/javascript'>{$this->contentArray['analytics.js']}</script>";
}
else{
	$analyticsString='';
}

$headStyle=$this->headStyle();
$route=Zend_Controller_Front::getInstance()->getRouter()->getCurrentRoute()->getDefaults();

$title=$this->headTitle();
if (isset($route['title'])){
	$title="<TITLE>{$route['title']}</TITLE>";
}

$this->applyStyles($this, $this->contentArray, array('skipSuperGlobal'=>true));

$headStyle=$this->headStyle();
$styleLinks=$this->headLink();
$javascript=$this->headScript();
$contentArray=$this->contentArray;
$viewContent=$this->layout()->content;

$headNav=$this->render('default/foundationComponents/base-head-nav.phtml');

$this->javascriptCalls('foundation.offcanvas.js', "js/foundation/");

$additionalJsLibItems=$this->javascriptCalls();

$layoutJavascript="


";

$userJavascript=$this->buildJqueryReadyCall($this->contentArray);

$outputString="<!doctype html>
<html class='no-js' lang='en'>
  <head>
    <meta charset='utf-8' />
    <meta name='viewport' content='width=device-width, initial-scale=1.0' />
    $title
    <script src='js/vendor/modernizr.js'></script>
	
	<style>html{font-size:62.5%;}</style>
    <link rel='stylesheet' type='text/css' href='css/animate.css/animate.css'/>
    <link rel='stylesheet' href='css/foundation.css' />
	$styleLinks
	
    $headStyle

  </head>
  <body>   
  
<!-- NAVIGATION SECTION ================================================== --> 
$headNav
<!-- CONTENT SECTION ================================================== --> 
$viewContent
<!-- SCRIPT SECTION ================================================== -->    
    <script src='js/vendor/jquery.js'></script>
    <script src='js/vendor/foundation/foundation.min.js'></script>
    <script src='js/vendor/node_modules/withinviewport/withinviewport.js'></script>
    <script src='js/vendor/jquery_downloads/jquery-bullseye-1-0b/jquery.bullseye-1.0.js'></script>
	
    $additionalJsLibItems
    <script>
      $(document).foundation();
	$(document).ready(function(){
		$layoutJavascript
		
	});
    </script>
    $userJavascript
    <script type='text/javascript'>
	/* <![CDATA[ */
		$(document).ready(function(){
			$(document).foundation();
		});
	/* ]]> */
</script>
  </body>
</html>";

$outputString=$this->translateUrls($outputString);
$outputString=$this->applyAllMacros($this->contentArray, $outputString);
$outputString=$this->mapServableToHash($this->contentArray, $outputString);

echo $outputString;