<?php

$serverComm=$this->serverComm;

$headTitle=$this->headTitle();
$headStyle=$this->headStyle();

$viewContent=$this->layout()->content;

$javascript=$this->headScript(); //note: call for steal.js is literal so it always executes first, others can count on it

$route=Zend_Controller_Front::getInstance()->getRouter()->getCurrentRoute()->getDefaults();
if (isset($route['title'])){
	$this->headTitle($route['title']);
}
else{
	$request = Zend_Controller_Front::getInstance()->getRequest();
	$this->headTitle($request->getActionName().'/')
		 ->headTitle($request->getControllerName());
}


//DROPDOWN MENU =========================================================================

$dropdownStyles="

	/*
		LEVEL ONE
	*/
	ul.dropdown                         { position: relative; float:right; z-index:1000;}
	ul.dropdown li                      { float: left; zoom: 1; }
	ul.dropdown a:hover		            { /*color: #000;*/ }
	ul.dropdown a:active                { /*color: #ffa500;*/ }
	ul.dropdown li a                    { display: block; padding: 4px 8px; /*border-right: 1px solid #333;*/
										  /*color: #222;*/ text-decoration:none; }
	ul.dropdown li:last-child a         { border-right: none; } /* Doesn't work in IE */
	ul.dropdown li.hover,
	ul.dropdown li:hover                { /*background: #F3D673; color: black;*/ position: relative; }
	ul.dropdown li.hover a              { /*color: black;*/ }


	/*
		LEVEL TWO
	*/
	ul.dropdown ul 						{ width: 220px; visibility: hidden; position: absolute; top: 100%; left: 0; }
	ul.dropdown ul li 					{ font-weight: normal; /*background: #f6f6f6; color: #000;*/
										  /*border-bottom: 1px solid #ccc;*/ float: none; }

										/* IE 6 & 7 Needs Inline Block */
	ul.dropdown ul li a					{ border-right: none; width: 100%; display: inline-block; }

	/*
		LEVEL THREE
	*/
	ul.dropdown ul ul 					{ left: 100%; top: 0; }
	ul.dropdown li:hover > ul 			{ visibility: visible; }
";

$ieStyle="ul.dropdown ul li					{ display: inline; width: 100%; } ";

$dropdownScript="
$(function(){
    $('ul.dropdown li').hover(function(){

        $(this).addClass('hover');
        $('ul:first',this).css('visibility', 'visible');

    }, function(){

        $(this).removeClass('hover');
        $('ul:first',this).css('visibility', 'hidden');

    });

    $('ul.dropdown li ul li:has(ul)').find('a:first').append(' &raquo; ');

});
";

$this->headScript()->appendScript($dropdownScript); //inlineScript() DOES NOT WORK. The code is never expressed.

$this->headStyle()->appendStyle($dropdownStyles);
$this->headStyle()->appendStyle($ieStyle, array('conditional'=>"lte IE 7"));


if(isset($this->contentArray['headNav.ini'])){
	$controlsString=$this->unorderedListForSelect(
		$this->contentArray['headNav.ini']['menu'],
		array('mainClass'=>'dropdown')
	);
}
else{
	$controlsString='';
}

$controlsString="
<div class='navBlock'>
	<div class='navMenus'>$controlsString</div>
</div>";



$elementList=(isset($this->contentArray['images']))?$this->contentArray['images']:array();
$headBanner=$this->contentArray['headBanner.html'];
	foreach ($elementList as $label=>$data){
		$headBanner=str_replace("images/$label", $data, $headBanner);
	}
$headBanner="<a href='http://<!baseDomain!>'>$headBanner</a>";
$headBanner=$this->translateUrls($headBanner);

if (isset($this->contentArray['siteDirectoryUrlList.ini'])){
$siteDirectory=$this->render('default/siteDirectory.phtml');
}
else{
	$siteDirectory='';
}

$contactFooter=$this->render('default/contactFooter.phtml');

$footer="
<div class='footerContainer'>
	<div class='footerSiteDrectoryBlock'>
		$siteDirectory
	</div>
	<div class='footerContactBlock'>
		$contactFooter
	</div>
</div>
";

$codeNavHtml=$this->showCodeNav($this->codeNav);

if (APPLICATION_ENV=='production'){
	$widgetScriptCall="<script type='text/javascript' src='/js/steal/steal.production.js?widgets'></script>";
}
else{
	$widgetScriptCall="<script type='text/javascript' src='/js/steal/steal.js?widgets'></script>";
}

if (APPLICATION_ENV=='production' && isset($this->contentArray['analytics.js']) && $this->contentArray['analytics.js']){
	$analyticsString="<script type='text/javascript'>
		{$this->contentArray['analytics.js']}
		</script>";
}
else{
	$analyticsString='';
}

//MAIN CONTENT SECTION =========================================================================
/*
font-family: 'Satisfy', cursive;
font-family: 'Open Sans', sans-serif;
font-family: 'Open Sans Condensed', sans-serif;
*/
$outputString="
	<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01//EN'
	   'http://www.w3.org/TR/html4/strict.dtd'>
	<html>

	<head>
	<META HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=UTF-8'>
	<link href='http://fonts.googleapis.com/css?family=Satisfy|Open+Sans:400italic,400,700|Open+Sans+Condensed:700' rel='stylesheet' type='text/css'>
	<link rel='stylesheet' type='text/css' href='http://yui.yahooapis.com/3.6.0/build/cssreset/cssreset-min.css'>
	<link rel='stylesheet' type='text/css' href='/css/baseCss/foundation.css'>
	<script type='text/javascript' src='js/jquery-1.6.4.js'></script>

	$headTitle

	<style type='text/css'><!--
		a {text-decoration:none;}
	--></style>

	$headStyle

	</head>

	<body >
	<table width=100%><tr><td align=center>
	$serverComm

	$headBanner
	$controlsString
	$viewContent

	$footer

	</body>

	$javascript

	$codeNavHtml
	</table>
	$widgetScriptCall
	$analyticsString
	</html>
";

$outputString=$this->translateUrls($outputString);
echo $outputString;