<?php

$serverComm=$this->serverComm;

$headTitle=$this->headTitle();
$headStyle=$this->headStyle();

$viewContent=$this->layout()->content;

$javascript=$this->headScript(); //note: call for steal.js is literal so it always executes first, others can count on it

$elementList=(isset($this->contentArray['images']))?$this->contentArray['images']:array();
$headBanner=$this->contentArray['headBanner.html'];
	foreach ($elementList as $label=>$data){
		$headBanner=str_replace("images/$label", $data, $headBanner);
	}
$headBanner="<a href='http://<!baseDomain!>'>$headBanner</a>";
$headBanner=$this->translateUrls($headBanner);

$siteDirectory=$this->render('default/siteDirectory.phtml');
$contactFooter=$this->render('default/contactFooter.phtml');

$footer="
<div style='margin-top:20px;background:#D7E3C4;width:1000px;min-height:200px;padding-top:20px;'>
	<div style='clear:both;overflow:hidden;'>
		$siteDirectory
	</div>
	<div style='clear:both;'>
		$contactFooter
	</div>
</div>
";

$codeNavHtml=$this->showCodeNav($this->codeNav);

//MAIN CONTENT SECTION =========================================================================

echo "
	<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01//EN'
	   'http://www.w3.org/TR/html4/strict.dtd'>
	<html>

	<head>
	<META HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=UTF-8'>
	<link rel='stylesheet' type='text/css' href='http://yui.yahooapis.com/3.6.0/build/cssreset/cssreset-min.css'>
	<link rel='stylesheet' type='text/css' href='/css/baseCss/foundation.css'>

	$headTitle

	<style type='text/css'><!--
		html {background:#E3EAD9;}
		a {text-decoration:none;}
	--></style>

	$headStyle

	</head>

	<body >
	$serverComm

$headBanner

	$viewContent

	$footer

	<script type='text/javascript' src='/js/steal/steal.js?widgets'></script>
	</body>

	$javascript

	$codeNavHtml
	</html>
";