
<?php
$route=Zend_Controller_Front::getInstance()->getRouter()->getCurrentRoute()->getDefaults();
if (isset($route['title'])){
	$this->headTitle($route['title']);
}
else{
	$request = Zend_Controller_Front::getInstance()->getRequest();
	$this->headTitle($request->getActionName().'/')
		 ->headTitle($request->getControllerName());
}



if (APPLICATION_ENV=='production' && isset($this->contentArray['analytics.js']) && $this->contentArray['analytics.js']){
	$analyticsString="<script type='text/javascript'>
		{$this->contentArray['analytics.js']}
		</script>";
}
else{
	$analyticsString='';
}

$contentString=$this->layout()->content;
$contentString=$this->mapServableToHash($this->contentArray, $contentString);

if (APPLICATION_ENV=='production'){
	$widgetScriptCall="<script type='text/javascript' src='/js/steal/steal.production.js?widgets'></script>";
}
else{
	$widgetScriptCall="<script type='text/javascript' src='/js/steal/steal.js?widgets'></script>";
}
$jqueryReadyScript=$this->buildJqueryReadyCall($this->contentArray);

 ?>
<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01//EN'
   'http://www.w3.org/TR/html4/strict.dtd'>
<html>
<head>
<META HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=UTF-8'>
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.6.0/build/cssreset/cssreset-min.css">
<link rel='stylesheet' type='text/css' href='/css/baseCss/foundation.css'>


<style type='text/css'><!--
	a {text-decoration:none;}
--></style>

<?php echo $this->headStyle(); ?>
</head>

<body>

<?php echo $this->serverComm; ?>

<?php echo $contentString; ?>

<?/*php echo $this->headScript()->appendFile('/js/steal/steal.js?widgets'); */?>

</body>
<!--
routeName: <?php echo $this->codeNav['routeName']; ?><br/>
controller: <?php echo $this->codeNav['controller']; ?><br/>
content: <?php echo $this->codeNav['contentDirPath']; ?><br/>
layout: <?php echo $this->codeNav['actualLayoutFullPath']; ?><br/>
-->	
<?php
echo $widgetScriptCall;
echo $jqueryReadyScript;
echo $analyticsString;
?>
</html>