<?

if (isset($this->contentArray['siteDirectoryUrlList.ini'])){
		$translatedUrlList=$this->contentArray['siteDirectoryUrlList.ini'];

		foreach ($this->contentArray['siteDirectoryUrlList.ini'] as $label=>$data){

			foreach ($data as $label2=>$data2){
				foreach ($data2['links'] as $label3=>$data3){
					$translatedUrlList[$label][$label2]['links'][$label3]['url']=$this->translateUrls($data3['url']);
				}
			}
		}


	$siteDirectory=$this->generateSiteDirectory($translatedUrlList);

	$siteDirectoryString='';
			foreach ($siteDirectory as $label=>$data){
				$siteDirectoryString.="
					<div style='float:left;margin-left:20px;margin-right:20px;'>
						<div style='font-weight:bold;border-bottom:1pt solid gray;margin-bottom:5px;'>{$data['title']}</div>
						<div>{$data['content']}</div>
					</div>
				";
			}
	echo $siteDirectoryString;
}