<?php

if (isset($this->contentArray['siteDirectoryUrlList.ini'])){
		$translatedUrlList=$this->contentArray['siteDirectoryUrlList.ini'];

		foreach ($this->contentArray['siteDirectoryUrlList.ini'] as $label=>$data){

			foreach ($data as $label2=>$data2){
				foreach ($data2['links'] as $label3=>$data3){
					$translatedUrlList[$label][$label2]['links'][$label3]['url']=$this->translateUrls($data3['url']);
				}
			}
		}


	$siteDirectory=$this->generateSiteDirectory($translatedUrlList);

	$siteDirectoryString='';
			foreach ($siteDirectory as $label=>$data){
				$siteDirectoryString.="
					<div class='sitemapBlock'>
						<div class='sitemapTitle'>{$data['title']}</div>
						<div class='sitemapContainer'>{$data['content']}</div>
					</div>
				";
			}
	echo "<table style='margin:0px auto 0px auto;'><tr><td align=center>$siteDirectoryString</td></tr></table>";
}