<?php
\Q\Utils::validateProperties(array(
	'validatedEntity'=>$this,
	'source'=>__file__,
	'propertyList'=>array(
		array('name'=>'codeNav'),
		array('name'=>'contentObj')
	)));

$request = Zend_Controller_Front::getInstance()->getRequest();
$this->headTitle($request->getActionName().'/')
     ->headTitle($request->getControllerName());

$this->contentArray=$this->contentObj->contentArray;



$firstString="<div style='margin:50px 0px 0px 200px;color:#436235;'>Welcome to cmERDC (".SITE_VARIATION.")</div>";


	$list=$this->contentArray['elements'];
	$outString2='';
	$count=0;
	foreach ($list as $label=>$data){
		$count++;
		$outString2.="$count) $data<br/>";
	}
	$outString2="<div style='color:gray;'>$outString2</div>";

$outString="
$firstString<p/>
<div id='ccc'>{$this->message} ({$this->codeNav['controller']}}</div>
{$this->contentArray['firstFile.txt']}<p/>
$outString2
";
?>XXXXX
<?php  echo $outString;?>

<div id='aaa'></div><div id='bbb'></div>